name: On demand release

on:
  workflow_dispatch:
    inputs:
      flavor:
        required: true
        type: choice
        description: "release type"
        options:
          - alpha
          - beta
          - rc
          - final
      ruby_version:
        required: false
        type: string
        description: The Ruby version to use
        default: '2.7.7'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        echo "coucou ${{ github.head_ref }}"
    - name: test
      if: github.ref == contains(github.head_ref, 'release/')
      run: |
        echo "coucou"
